Docs: Resolve a docutils warning
The warning is:

```
sentence_transformers/sentence_transformer/losses/multiple_negatives_ranking.py:
docstring of sentence_transformers.sentence_transformer.losses.multiple_negatives_ranking.MultipleNegativesRankingLoss:52:
ERROR: Unexpected indentation. [docutils]
```

RST requires nested lists to be separated by blank lines.