Docs: Resolve a docutils warning
The warning is:

```
sentence_transformers/sentence_transformer/losses/cached_multiple_negatives_ranking.py:
docstring of sentence_transformers.sentence_transformer.losses.cached_multiple_negatives_ranking.CachedMultipleNegativesRankingLoss:46:
ERROR: Unexpected indentation. [docutils]
```

RST requires nested lists to be separated by blank lines.